;;; fig-ideasguy --- Ideas Guy -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(require 'dash)
(require 's)
(require 'f)
(require 'ht)
(require 'json)
(require 'request)

(defconst fig//past-stream-titles
  '(("esolangs, entity" . "exotic languages Learned And Spoken. @LCOLONQ visibly risibly touring the MENAGERIE entity research session GO. discovering various beings!")
    ("christmas tree, genealogy" . "timeless GENEALOGY of @LCOLONQ - exploring (+ decorating?) the Colonq family Midwinter Festival Themed Tree. reading in a big comfy armchair")
    ("christmas" . "The Dance Of The @LCOLONQ Fairy. getting doubtlessly dareisay downright FESTIVE today, Computer. appearance from Noted ClonkHead Santa Claus")
    ("cultivation" . "The Golden Shining Heart Of @LCOLONQ. optimizing our Prana Levels and maximizing blessings. pure-cored BEAUTIFUL energy waves DIRECT to you!")
    ("electricity" . "back with a VENGEANCE! @LCOLONQ vs. the concept of Electricity. they never expect my HIDDEN POWER GROUND. Zeus will fall today. believers!??")
    ("thanksgiving, forth" . "Forthsgiving misgivings. Expressing gratitude with @LCOLONQ. giving every member of staff a COMPLETE and ALL_ENCOMPASSING federal pardon. :3")
    ("geometry" . "learning about shapes and colors - @LCOLONQ RHOMBUS STYLE BEGIN NOW. (the thing that we are going to do is to understand \"\"shader\"\"). okay!!")
    ("friendship, return" . "having fun on the computer with my friends (you). Experience Ego Death With @LCOLONQ, Today. it's been 4 days but it feels like 99999 years?")
    ("moving" . "alchemizing KINESIS from potentia with @LCOLONQ. The End Of LCOLONQ, Also (100% real confirmed verified). curriculum mortis, my dear oomfie.")
    ("remote viewing" . "putting \"Animé\" in YOUR terminal, computer. @LCOLONQ Remote Viewing Telesthesia ESP paraPSYchology session. unleashing ANCIENT CURSE on oomf")
    ("november" . "No NoLCOLONQ November. Today we return to Neo Earth and complete an abandoned task... pitiless purgation, debonair denial. The Path Of Joy!?")
    ("halloween" . "fearful festivities forthcoming, Fomputer. @LCOLONQ's \"Idol Nightmare\". in pursuit of the lord of the pumpkin court. Summoning Salty Dogs :)")
    ("pumpkin, curse" . "carving PUMPKIN with @LCOLONQ. The Way That We Will Carve The Pumpkin Is Deeply Upsetting To Me, PERSonally. gruesome ghoulish gonzo !oomfie")
    ("forth" . "mlg Forth gameplay, today we EMULATION. despicable computerized goblins. Swordplay In The Gardens Of Lunar Perfection. i really like you :))")
    ("twitchcon, las vegas" . "Lisp LIVE on twitchCon show floor?? Will it be a BONUSx3 for @LCOLONQ, or are we doomed to eternal failure it's over o7. Find Out Now, Oomf!")
    ("forth, emulation" . "learning \"\"Forth\"\". EMULATION is the sincerest form of flattery, @LCOLONQ. quest markers OFF minimap OFF hardcore ironman gameplay... !today")
    ("wishes" . "what does it mean to make a wish, Computer? @LCOLONQ's Secret Wish In The Morning. a comprehensive theory of \"Gamer\": Gestalt. delicious yum")
    ("rings" . "forging RINGS with @LCOLONQ. Practicing \"Celebrimbor's Art\", today. you better be ready to go OCTOPUS STYLE, so as to hold these rings. hiii")
    ("housing" . "solving \"The Housing Crisis\" (initiative: @LCOLONQ). living together in a mansion drinking delicious tea, Computer. affordable Safe CLEAN C:")
    ("fusion" . "HYBRIDIZING chatters. The Island of Dr. Clonkeau. @LCOLONQ's animal jurisprudence. it's going to get,,,, dare I say, GHOULISH. me<3computer?")
    ("friendship" . "making a new friend on the \"Computer\" with @LCOLONQ. AN Education on what it means to be O.O.M.F.I.E. The Refined Social Graces Of El Clonqu")
    ("game development" . "creating \"video gaming\" Live with The Computer (and also with @LCOLONQ). delectable tasty treats for you today, Clonk's Head. !oomfie !oomfi")
    ("metamorphosis" . "the metamorphosis... Witness My Morph, Computer. Witness My Morph, @LCOLONQ. it's tactical Animé action hour(s). why not !oomfie? clonk head")
    ("war" . "war never changes, computer... @LCOLONQ And Emacs Become Rosen Maiden Anime Otaku Gamer?? an unfortunate encounter with GDB, and more! xoxoX")
    ("one thousand" . "one MILLENIUM of @LCOLONQ xxxCELLENCE! The Quest for Joel, The Quest for Party Hat. celebrating the ultimate victory of COMPUTER. !oomfie <3")
    ("bridge repair" . "The Lost Secrets oF The Antique Past with your friend @LCOLONQ. enter my MIRROR WORLD. i love you and i love computing :) bridge repair too?")
    ("gladiator" . "Blood on the sand. Maybe @LCOLONQ's? who can say... My Sword Hand Twitches, Computer. prototyping a VidGame within \"GNU EMAXXX\". I Love You?")
    ("polar exploration" . "An Expedition with @LCOLONQ. forever OUTWARD and UPWARD. getting devoured by polar bears and penguins etc etc. Just like that, Computer. >:]")
    ("baldur's gate" . "clonk and bald torture. enjoying some pleasant gaming with @LCOLONQ. Surely There Will Be Nothing ABNormal about This Gaming, No? fufufufufu")
    ("heist" . "The Great Content Heist - will @LCOLONQ Steal Your Heart? organ sales TUTORIALIZING. converting other streamers into Lettermen. !commands :)")
    ("music" . "Is Chat An Instrument? with your friends The Computer, @jakecreatesstuff, and @LCOLONQ. tripping the light FANTASTIC with you, computer!")
    ("stream key" . "leaking my stream key. hey guys I'm @LCOLONQ and I want you to have this Cool New OAuth2 Bearer Token. anticipate GRIEVANCES, ClonkHead. :)")
    ("gentoo, speedrun" . "Installing Gentoo with @LCOLONQ. it's also a \"speedrun\" you know what that means. They've Never Seen A Sicko Like Me, Computer. | !commands")
    ("gorilla" . "Gorilla Stream. camouflaged UP in the JUNGLE. going bananas. Jamie, pull that up. I need to fill space so I wrote this instead of !commands")
    ("speedrun" . "Gentoo Speedrun Prep. Me and @LCOLONQ. about time i got a lucky break in this game. Splits and PBs. Fanatical Gaming eXXXcellence !commands")
    ("illness" . "curing the POX with @LCOLONQ: The Illest. Disgusting implements applied to cadavers. Finishing our residency. we are SO BACK!!!! | !commands")
    ("las vegas" . "@LCOLONQ: New Vegas. Live from the city of Spin. Discussion Topic: Fantasia $$ BONUS BONUS BONUS $$ do NOT get this one twisted | !commands")
    ("breeding" . "breeding with @LCOLONQ. identifying Indigo Children. absolutely sickening amounts of text. Animal, Vegetable, Miracle: Numerical | !commands")
    ("announcement" . "An Announcement. @LCOLONQ Remake TARTIGRADE. large movements deep beneath the earth's crust. Cosmic Forces Operating In Unison For LCOLONQ!")
    ("debut" . "new model debut. @LCOLONQ Season 1 GRAND FINALE. Power Ranking Battles, intense gaming. Probably a whole bunch of Emacs Lisp too | !commands")
    ("training" . "training in the ruins of a crumbling polity. @LCOLONQ INVINCIBLE STRENGTH ARC. season 1 penultimate episode. Getting Crusty... | !commands")
    ("duels, baths" . "The Revivification Of @LCOLONQ. let's go to the spa together. Formalized D-D-D-Duels. sick little ogres. We're So Back, No? No? | !commands")
    ("afterbirth" . "999' Beneath The Cold Earth. @LCOLONQ AFTERBIRTH. Delving, protected by our boon companions. Viscous OOZES. DDDemonaic DDDevices | !commands")
    ("birth" . "birthing stream, creating ORGANISMS with @LCOLONQ. The Long Long Gestation. CULINARY EXCELLENCE. Devious sSsSchemeSsSs. fufufufu !commands")
    ("conception" . "Forming Human Souls from CYBERCLAY. horrid little goblin chats UNCEASINGLY. A Complete Primer In The Ways Of War. I love you <3 !commands")
    ("obliteration" . "@LCOLONQ preaches OBLITERATION. Elisp be my god. Hypothetical Operation: (reverse \"ZENTREYA\"). eprit de corps MAXIMIZATION. chat !commands")
    ("beach" . "In Memoria Miseria. On THE BEACH with @LCOLONQ (he's your buddy). We'll be swimmin around and enjoying the summer. Burgs and dogs. !commands")
    ("bible" . "None of those words are in the Bible, @LCOLONQ. Linguistic trickery, creating problems for that rat fink Webster. Emacs Gang. !commands")
    ("party" . "party time, @LCOLONQ. Obedience will be rewarded. Twisted psychological games. \"So obscene it should be illegal.\" !commands")
    ("safari" . "\"On Safari\". @LCOLONQ on the move! Exploring a novel environment full of (dangerous!?) flora and fauna. Suboptimal meteorology. | !commands")
    ("three dimensions" . "@LCOLONQ finds the third DemenSion. having fun with my FRIENDS! on the computer. perhaps some Classic Info Computing? xD XD Xd | !commands")
    ("obliteration" . "OBLITERATION beckons, @LCOLONQ. 999 hour slayertaskmaxing, profound truths uncovered. Welcome Back, ClonkHead. | !commands")
    ("rhetoric" . "the Æncient Ært of RHÆTORIC. the computer will speek frealy and fluently. Along the way, we'll learn things about each other and our bodies.")
    ("dungeon" . "fun with the machine. @LCOLONQ C_C_C_COMBO MEAL. Perhaps a glance at the DunGeons? Who Will Be The Dungeon Master? find out here, today")
    ("isekai" . "@LCOLONQ isekai adventures, deep dark fantasies, KILLER +3 Telepathic Swords with X-Ray Vision. You haven't seen anything like it since HBO.")
    ("poetry" . "Touching grass with your dear friend, @lcolonq.")
    ("corporate" . "@LCOLONQ shareholders' meeting. the info YOU need to SURVIVE. elite corporate strategems and tactiCOOL_TIPS. Will You Be The Water Cool God?")
    ("affiliate" . "journey into a magical færie forest with @LCOLONQ and GNU Emacs. out here AFFILIATED and ready to enjoy the spoils of war. !commands (!!!)")
    ("chat" . "grafting my twitch chat oomfies to emacs. sponsored by @LCOLONQ. a hideous mass of glyphs wriggling away in the dark. BONUS BONUS BONUS")
    ("twitch integration" . "the stream that makes you old. going there, with your friends @LCOLONQ and the computer. making twitch stuff. \"Lab Sesh\". PROFOUND_ARROGANCE")
    ("debugging" . "confused online, together. dlate dnight debugging sesh gamers, let's get to it. the relevant key-phrases: EMACS POKEMON AI @LCOLONQ HI ILU<3")
    ("ai" . "creating man-made horrors beyond my comprehension. yeah, i'm thinking we're back. emacs @LCOLONQ visual asmr CLOUTED UP BRICKED UP UNSTOPPAB")
    ("emacs, pokemon" . "enter the ANger Vortex... welcome to my depraved nightmare realm... (im babbling about emacs and pokemon again lol lmao even)")
    ("emacs, pokemon" . "emacs gaming. we're so back oomfies. RELENTLESS VICTORY. ancient laws REVEALED Tap into sweet deals and delicious perks with the new Denny’s")
    ("emacs, pokemon" . "thursday thnight thacking. emacs lisp and chill. excellent vibrations and droll remarks. pocket monsters discussion.")
    ("valentines" . "cozy valmentimes emacs lisp evening gone SENSUAL. only elite wizard-commandos allowed entry. dorky rambling ASMR binaural beats to study and")
    ("ai, pokemon" . "\"A.I.\" today. electronic macs. perhaps other mishaps and elite gambits. free money as always.")
    ("oubliette" . "getting up to some horses's shit in the OUBLIETTES. exclusively true strapping warriors and effervescent wizards allowed entry")
    ("pokemon" . "pokemon emerald but we're writing a bot $FREE CASH$ rooting around in the guts of the computer $COOL WOW$")))

(defun fig//generate-stream-title (theme k)
  "Given THEME, generate a stream title and pass it to K."
  (fig/ask
   theme
   k
   "Given a theme, produce a stream title for an LCOLONQ Twitch stream. LCOLONQ is a programming streamer who uses Emacs, Lisp, and other obscure technologies. LCOLONQ stream titles tend to be a bit deranged and silly, containing many oblique and hard-to-understand references to the theme. Their capitalization is erratic, ranging from lowercase to uppercase to titlecase at random. The titles never contain emoji. They frequently use the words Joel, oomfie and Computer. They always include @LCOLONQ at least once."
   (-map #'car fig//past-stream-titles)
   (-map #'cdr fig//past-stream-titles)))

(provide 'fig-ideasguy)
;;; fig-ideasguy.el ends here
