
(defconst fig//era-names
  `((medievaltimes
     "Grey"
     "Æbbe" "Ælfflæd" "Ælfgar" "Ælfgifu" "Ælfheah" "Ælfnoð" "Ælfræd"
     "Ælfric" "Ælfsige" "Ælfstan" "Ælfswiþ" "Ælfþryð" "Ælfthryth"
     "Ælfweard" "Ælfwig" "Ælfwine" "Ælfwynn" "Ælred" "Æsc" "Æþelbeorht"
     "Æðelberht" "Æðelflæd" "Æthelflæd" "Æðelfrið" "Æðelmær" "Æthelnoð"
     "Æðelræd" "Æþelræd" "Æthelred" "Æðelric" "Æthelric" "Æðelstan"
     "Æthelstan" "Æðelþryð" "Æthelthryth" "Æthelweald" "Æthelweard"
     "Æðelwine" "Æthelwine" "Æðelwulf" "Bada" "Beorhtric" "Beorhtsige"
     "Beornræd" "Botwulf" "Burgheard" "Ceadda" "Cenhelm" "Cenric"
     "Ceolmund" "Cerdic" "Cola" "Cuthberht" "Cynebald" "Cyneburg"
     "Cyneburga" "Cynefrith" "Cynefrið" "Cyneheard" "Cynemær" "Cyneric"
     "Cynesige" "Cyneweard" "Deorwine" "Dudda" "Dunstan" "Eadberht"
     "Eadburg" "Eadburga" "Eadgar" "Eadgifu" "Eadgyð" "Eadmund" "Eadric"
     "Eadwald" "Eadweard" "Eadwig" "Eadwine" "Eadwulf" "Ealdberht"
     "Ealdgyð" "Ealdhelm" "Ealdræd" "Ealdwine" "Ealhhere" "Ealhstan"
     "Ealhswiþ" "Eardwulf" "Eastmund" "Ecgberht" "Eoforheard" "Eoforhild"
     "Eoforwine" "Eormenhild" "Friðuswiþ" "Glædwine" "Godgifu" "Godiva"
     "Godric" "Godwine" "Heard" "Hereward" "Hereweald" "Hild" "Hilda"
     "Hildræd" "Hroðgar" "Hrothgar" "Hroðulf" "Hrothulf" "Hunbeorht"
     "Leofdæg" "Leofflæd" "Leofgyð" "Leofric" "Leofsige" "Leofstan"
     "Leofwine" "Mærwine" "Milburga" "Mildburg" "Mildgyð" "Mildþryð"
     "Osbeorht" "Osbeorn" "Osberht" "Osgar" "Osmund" "Osweald" "Oswine"
     "Pæga" "Sæwine" "Sigeberht" "Sigeweard" "Stithulf" "Sunngifu"
     "Swiðhun" "Tata" "Uhtric" "Wærmund" "Waltheof" "Wassa" "Wealdhere"
     "Wealdmær" "Wealhmær" "Wemba" "Wigberht" "Wigheard" "Wigmund"
     "Wigstan" "Wihtburg" "Wilburg" "Wilburh" "Wilfrith" "Wilfrið"
     "Wilheard" "Wilmǣr" "Wine" "Winfrith" "Winfrið" "Withburga"
     "Wulfflæd" "Wulfgifu" "Wulfnoð" "Wulfric" "Wulfrun" "Wulfsige"
     "Wulfstan" "Wulfwynn" "Wynnflæd" "Wynnstan")
    (ageofsail
     ,@(append
        (list "Roberts" "Sparklez" "Johnny" "Crunch" "Jack" "Nathaniel" "anakata" "Davy" "Morgan" "Vriska" "Monkey" "Bob")
        (--map (s-concat (s-titleize (s-replace " " "" it)) "beard") (defined-colors))))
    (renaissance
     "Leonardo" "Raphael" "Donatello" "Michelangelo"
     "Amp" "Volt" "Mustyfears" "Monaspets" "Monaspets" "Volt" "Volt"
     "Acoz" "Abrahamlincoln" "Aceinvestigativereporter" "Actiontoad"
     "Admiralbobbery" "Aerodent" "Akiki" "Akuiwagumi" "Akuiwagumisleader"
     "Alarmclockobstaclealarmclock" "Alarmmonkey" "Alberteinstein" "Alena"
     "Alex" "Alimustafa" "Alienmariopartyseriesalien" "Alkementor"
     "Allegra" "Allie" "Alligatordundeecharacteralligatordundee"
     "Captainolimaralph" "Alyssamilano" "Amadeuswolfgeist" "Amyamyrose"
     "Katanaana" "Anascrew" "Ancientminister" "Andrewiverson" "Angelica"
     "Angelo" "Anglerpoplin" "Annehathaway" "Anonster" "Antasma"
     "Anthonyscapelli" "Appleby" "Apprenticetorteapprentice" "Aqualea"
     "Arekuhakase" "Arfur" "Arich" "Aristotle" "Armoredharriers"
     "Armydillo" "Armyhammerbro" "Artanddecoart" "Ashley" "Aster" "Augie"
     "Auntluigeena" "Auntmarie" "Awab" "Axemblack" "Axemgreen" "Axempink"
     "Axemred" "Axemyellow" "Azalea" "Bcoz" "Blocker" "Baboom" "Babs"
     "Babybowser" "Babydaisy" "Babydonkeykong" "Babykong" "Babyluigi"
     "Babyluma" "Babymario" "Babypeach" "Babyrosalina" "Babywario"
     "Bachelor" "Badadder" "Baffle" "Bahamutt" "Bakermariopaintbaker"
     "Balloonfighter" "Hammabammaandflarebammabamma" "Bananafairyprincess"
     "Bananaqueen" "Bandyandy" "Banktoad" "Banjo" "Barb" "Barbos"
     "Barfatroniclavachomper" "Barnacle" "Baronbrrr" "Barry" "Barter"
     "Bashmaster" "Battlet" "Battrahanachan" "Bayonetta" "Bazaar"
     "Bazooka" "Bea" "Beanmobilegolfbean" "Beanbeantroop"
     "Beanstalkcharacterbeanstalk" "Beardonkeykonglandiiibear" "Bedrock"
     "Bedsmith" "Beef" "Beep" "Beetlecharacterbeetle" "Beetlemaniatoad"
     "Belcha" "Beldam" "Belinda" "Kritterdonkeykongbellkritters" "Belltop"
     "Belome" "Benjaminfranklin" "Benny" "Bestovius" "Bessiebass" "Beth"
     "Betsy" "Bianca" "Biffatlas" "Bigbadwolf"
     "Bigberthafilmcharacterbigbertha" "Bigbird" "Bigbulletbill"
     "Bigbungeepiranha" "Bigburtbros" "Bigdaddyofbloopersurfing"
     "Bigkamukamu" "Biglanternghost" "Bigmassif" "Bigmri" "Bigpaintstar"
     "Bigpenguin" "Bigpiranhaplant" "Bigtop" "Bigcharacterbigthecat"
     "Biggerboo" "Bingo" "Boardssupermariogalaxybillboard" "Bink"
     "Biokinton" "Birdcharacterbird" "Birdley" "Birdo" "Bizzy" "Bjrn"
     "Blablanadon" "Blackboo" "Blackdog" "Blackdragon" "Blackjewel"
     "Blackmage" "Koopabrosblackninjakoopa" "Blanka" "Blappy" "Blarfle"
     "Blazeblazethecat" "Bleak" "Bleu" "Blinky" "Blittyblitties" "Blizza"
     "Blizzardcharacterblizzard" "Blizzardmidbus" "Blizzaurus" "Blizzy"
     "Bloat" "Blobule" "Blooey" "Bloomsday" "Blubi" "Blue"
     "Redbluegoombabrosbluegoomba" "Yellowtoadandbluetoadbluetoad"
     "Blueythewalrus" "Blunder" "Blusterkong" "Bob"
     "Bobombpapermariotheorigamikingbobomb" "Bobombsquadgroupbobombsquad"
     "Bobomba" "Bobo" "Boddle" "Bogmire" "Bogmonster" "Bomberman"
     "Bomberto" "Bombette" "Bonechill" "Boneheads" "Bonescharacterbones"
     "Bonetail" "Bonneterbiologist" "Boomariopartyboo" "Boodin"
     "Bookertwashington" "Boolossus" "Boom" "Boomboom"
     "Boomersupermariorpglegendofthesevenstarsboomer"
     "Boomerdonkeykongcountrydixiekongsdoubletroubleboomer"
     "Boomersuperpapermarioboomer"
     "Listofboosinluigismansionboosinluigismansion" "Booster" "Bootler"
     "Borderbro" "Boshi" "Bottles" "Bouldergeist" "Bowletta" "Bowser"
     "Bowser" "Bowserjr" "Bowsermemoryml" "Bowsersbrother"
     "Listofimpliedcharactersbowsersfatherbowsersfather" "Bowsersmother"
     "Listofimpliedcharactersbowserssisterbowserssister" "Bowyer" "Boxboy"
     "Boywariowaresmoothmovesboy" "Bozzo" "Bramblecharacterbramble"
     "Brash" "Brawldoll" "Briansaturdaysupercadebrian"
     "Brianmariotennisbrian" "Brianbonsall" "Brickle" "Bridgetthebaker"
     "Brighton" "Britta" "Brklncouple"
     "Listofimpliedcharactersbritneybritney" "Brobot" "Broggy"
     "Broquemadame" "Broquemonsieur" "Brothersbear" "Bruce"
     "Brutiusmaximusgrouchimus" "Bub" "Bubulber" "Bubbles"
     "Bubblescluclulandbubbles" "Bubbleplant" "Bubblertheoctopus"
     "Buckies" "Bud" "Budandmissysmother" "Buddy" "Bumpercharacterbumper"
     "Bundt" "Bunsen" "Burtthebashful" "Businessman"
     "Butterfingerscharacterbutterfingers" "Buzzcharacterbuzz" "Buzzar"
     "Buzzardcharacterbuzzard" "Bwaluigi" "Bwario" "Byleth" "Cackletta"
     "Cactuar" "Cactusking" "Candyclone" "Candykong" "Cannonpianta"
     "Cappy" "Captain" "Captainabidab" "Captainboo" "Captainclump"
     "Captainfalcon" "Captainfishook" "Captaingills"
     "Captaingoombamarioluigiseriescaptaingoomba"
     "Captaingoombamariopartycaptaingoomba" "Captainkoopatroopa"
     "Captainolimar" "Captainorion" "Captainshyguymariopartycaptainshyguy"
     "Captainshyguymarioluigiseriescaptainshyguy" "Captainskull"
     "Captainsyrup" "Captaintode" "Captaintoad" "Cardconnoisseurtoad"
     "Caresawayan" "Carlton" "Carpaccio" "Carrie" "Carrot" "Carson"
     "Catbat" "Catherinedickens" "Chad" "Chakron" "Chambrea"
     "Chanterellethesupermariobrosmoviechanterelle" "Chan" "Chapbluechap"
     "Chapgreenchap" "Chas" "Charlesdickens" "Charlesgasparddelarive"
     "Charlie" "Charlieton" "Charmycharmybee" "Charold" "Chauncey" "Chaz"
     "Cheepskipper" "Cheepy" "Chefshimi" "Chefsoulffl" "Chefspore"
     "Cheftorte" "Cher" "Cherie" "Chester" "Chetmariotennispowertourchet"
     "Chetsuperpapermariochet" "Chetrippo" "Chiefchilly"
     "Listofimpliedcharacterschiefquimbychiefquimby" "Chillbully"
     "Chirako" "Chdossun" "Chochinunkou" "Chompcountry" "Chopperbird"
     "Chrsama" "Cicada" "Cindertoad" "Chortlebot" "Chosentoads" "Chris"
     "Chrom" "Chuckquizmo" "Chuckie" "Chuckleroot" "Chuckolator" "Chunli"
     "Chunkykong" "Clawgrip" "Clapper" "Clay" "Claymorton" "Cleftor"
     "Clem" "Cleopatra" "Clerk" "Cloaker" "Clockworksoldiers" "Clog"
     "Cloudncandy" "Cloudstrife" "Cloudjin" "Clownaround" "Costarluma"
     "Coachmariopartyadvancecoach" "Coachsupermariogalaxycoach"
     "Coachsupermarioodysseycoach" "Coinfish" "Coloredpencils" "Comettico"
     "Commandershroob" "Congazuma" "Conker" "Conn" "Constanzemozart"
     "Cookoobird" "Corkandcask" "Corporalparaplonk" "Corrin" "Cortez"
     "Cosmicmariocosmicluigi" "Cosmicmario" "Cosmicspirit" "Countbleck"
     "Countcannoli" "Countdown" "Coursebot" "Cowboyjed"
     "Countzoltandracula" "Crabcharactercrab" "Cractus" "Crankykong"
     "Listofimpliedcharacterscrankykongsgreatgrandfathercrankykongsgreatgrandfather"
     "Crateguy" "Crawdaddy" "Crazyhand" "Creamcharactercreamtherabbit"
     "Crimewaveclyde" "Croco" "Crystalking" "Cuby" "Cuckoocondor" "Cudge"
     "Culex" "Cupking" "Curator" "Cursa" "Curt" "Cutter" "Cybele"
     "Cyndilauper" "Cyrrus" "Czardragon" "Dada" "Dancingjewels"
     "Dancingmonkeys" "Danet" "Daniella" "Danny" "Daphne" "Darkbowser"
     "Darkfawful" "Darklordhumgree" "Darkpit" "Darksamus" "Darkstar"
     "Darkstarcore" "Darkly" "Dashell" "Davidgrenewetzki" "Davidhorowitz"
     "Davybones" "Dazzle" "Deadbones" "Dealindelbert" "Deborahread"
     "Artanddecodeco" "Dedar" "Demonhead" "Deepcutstoad" "Desertwanderer"
     "Destructors" "Devilshead" "Dhalsim" "Dharkon"
     "Diamondacademyaudience" "Diamondcityroughs" "Diamondpolice"
     "Diamondtroll" "Diddykong" "Dieter" "Dimentio" "Dingaling"
     "Dinopiranha" "Dinomighty" "Thedinosaurs" "Director" "Dirkdrainhead"
     "Dixiekong" "Djcheeptuna" "Djphantasmagloria" "Docfreud" "Doctor"
     "Dodo" "Doet" "Dogadon" "Dogu" "Dollboy" "Domino" "Donbongo"
     "Donlloyd" "Donpianta" "Donthesparrow" "Donzunna" "Donkeykong"
     "Donkeykongjr" "Donny" "Doopliss" "Dootdootsisters" "Hsnanddsndsn"
     "Dorguythefirst" "Dorguythesecond" "Dorguythethird" "Doris" "Dottie"
     "Doubletusk" "Dralex" "Drcrygor" "Dreggman" "Drfrankenstein"
     "Drlight" "Drnerdnick" "Drpayne" "Drpotter" "Drsheldon"
     "Drsigmundfruitcake" "Drsnoozemore" "Drsporisvonfungenstein"
     "Drtgarden" "Drtoadley" "Drtoadleysintern" "Drtoby" "Drtopper"
     "Drvent" "Drwaldobloom" "Drwily" "Draglinger" "Drago" "Dragonlord"
     "Dragonzamasu" "Dreadkong" "Dreamstonesoul" "Dreamyluigi"
     "Dribblespitzdribble" "Drillbit" "Driver"
     "Driverthesupermariobrosmoviedriver" "Drumstickcharacterdrumstick"
     "Dryad" "Drybowser" "Dualdragon" "Duckhuntduo" "Dinoridersduke"
     "Dukeofalenon" "Dumbdrum" "Dunk" "Dupree" "Dweezil" "Dyllis"
     "Dynamite" "Omegaeomega" "Ec" "Eddiethemeanoldyeti" "Eddythemask"
     "Edge" "Edison" "Edmundhalley" "Eelymouth" "Eggmannega"
     "Egyptiankoopa" "Einstein" "Elden" "Elder" "Elderprincessshroob"
     "Eldershrooboid" "Eldstar" "Eldream" "Electrician" "Electroblooper"
     "Elephantogre" "Ella" "Elliesuperpapermarioellie" "Ellie" "Elliemae"
     "Elroy" "Elvingaddpast" "Elvinparsley" "Elvira" "Elvispresley" "Emi"
     "Emily" "Emoglobin" "Emperored" "Enguarde" "Enmadai"
     "Erikbaleogandolaf" "Erniehudson" "Espioespiothechameleon" "Eve"
     "Evildinosaur" "Evilwoody" "Excessexpressconductor"
     "Excessexpressengineer" "Excessexpresswaitress" "Expresso" "Exor"
     "Exterminator" "Eyerok" "Factorychief" "Fahroutpostmayor" "Fakewario"
     "Falcolombardi" "Fankidsintheshop" "Fauster" "Fava" "Fawful" "Fay"
     "Fearsome" "Ferdinandmagellan" "Ficet" "Fierydinopiranha" "Firegod"
     "Firenecky" "Firebrandandthunderhandfirebrand" "Fishmael"
     "Fivefunguys" "Flabboys" "Flaky" "Flamm"
     "Hammabammaandflareflareflare" "Flavio" "Fleep" "Fleetroc" "Flight"
     "Flimm" "Flintcragley" "Flit" "Maudeandfloflo" "Fludd" "Fluffy"
     "Flurl" "Flurrie" "Fluzzard" "Foreman" "Foremanspike"
     "Listofimpliedcharactersfourheroesfourheroes" "Foxfoxmccloud"
     "Fracktail" "Francesca" "Francis" "Francisdrake"
     "Frankensteinsmonster" "Frankie" "Franky" "Fred" "Frederickdouglass"
     "Fret" "Friendlyfloyd" "Frogsage" "Frogsagesstudent" "Froggy" "Fronk"
     "Frostt" "Frosty" "Fryguy" "Fugu" "Funkykong" "Ftbot"
     "Thefuzzfuzzthe" "Fuzzipede" "Gabbro" "Galeem" "Galileogalilei"
     "Galrog" "Gamebot" "Gameguy" "Ganon" "Ganondorf" "Garamond"
     "Garbageboy" "Gardener" "Garf" "Garro" "Garson"
     "Garymariotennispowertourgary" "Garysuperpapermariogary" "Gassox"
     "Gattaimonster" "Gaz" "Gearmogold" "Gearmosilver" "Gene" "Generalguy"
     "Generalklump" "Generalwhite" "Geniethesupermariobrossupershowgenie"
     "Geniewariolandsupermariolandgenie" "Genieofthelamp" "Geno"
     "Georgewashingtoad" "Georgewashington" "Georgewashingtoncarver"
     "Gerspard" "Ghastlyking" "Ghostsupermariogalaxyghost"
     "Ghostwariolandsupermariolandghost" "Ghostwariolandiibossghost"
     "Ghostwariolandghost" "Ghostt" "Ghostsofchristmas" "Giantbee"
     "Giantbirdo" "Giantclam" "Giantsnake" "Giantspearman" "Giantspider"
     "Giantvikingkremling" "Giantwiggler" "Gigabowser"
     "Boardssupermariogalaxygilboardgilboard" "Giuseppe" "Gladys"
     "Glimmer" "Gloathog" "Glom" "Gloomer" "Gloomtail" "Gnaw" "Gob"
     "Gobblegut" "Goldfuzzy" "Goldbob" "Goldendiva" "Gondolier"
     "Goodstyle" "Thegoodwillambassador" "Gooigi" "Goomgoom" "Gooma"
     "Goomama" "Goombamariopartygoomba"
     "Goombasuperpapermariocharactergoomba" "Goombabros" "Goombaidols"
     "Goombamummy" "Goombaria" "Goombario" "Goombette" "Goombetty"
     "Goombella" "Goombob" "Goomboss" "Goomez" "Goomfrey" "Goomhilde"
     "Goompa" "Goompapa" "Goomther" "Gooperblooper" "Goose" "Goosey"
     "Goro" "Gorochan" "Gourmetguy" "Grace" "Grambi"
     "Grammaredandgrammagreengrammagreen"
     "Grammaredandgrammagreengrammared" "Grammatoadstool" "Grampie"
     "Gramps" "Grandma" "Grandmamario" "Grateguy" "Gravetusk"
     "Greatsunflower" "Green" "Koopabrosgreenninjakoopa" "Greenfist"
     "Greenkroc" "Greninja" "Grifty" "Grubba" "Gruntcharactergrunt"
     "Guarddoor" "Guppy" "Gus" "Gunyolk" "Gururinknight" "Hal" "Hakkunsai"
     "Hammabammaandflarehammajammahammajamma" "Hammerheadbros"
     "Handitovers" "Hardhat" "Hardroc" "Harhall" "Harleyq"
     "Harrymariogolfharry" "Harrymariotennisseriesharry"
     "Harrypapermarioharry" "Harrythesupermariobrossupershowharry"
     "Harryblackstonejr" "Harryh" "Haruji" "Hassan" "Hayzee"
     "Headlesssnowman" "Healslime" "Heavysmoker" "Hectorthereflector"
     "Hefft" "Helen" "Heliowariolandhelio" "Hellengravely" "Helmutkohl"
     "Helvetica" "Hen" "Henryandorville" "Henryford" "Herbt" "Herbert"
     "Hercufleas" "Herlocksolmes"
     "Hermantheadventuresofsupermariobrosherman" "Hermansmirch"
     "Hermieiii" "Hero" "Heronicus" "Herringway" "Hidechan" "Hidon"
     "Highoctanehippo" "Hildy" "Hinky" "Hinttoad" "Hippo" "Hiyoihoi"
     "Hoggus" "Holepunch" "Hollijollimayor" "Hollykoopa" "Hollymackerel"
     "Honeyqueen" "Hongo" "Hoo" "Hoodedrobin" "Hoodin" "Hoofer"
     "Hoohooros" "Hookbillthekoopa" "Hooktail" "Hoot" "Horkusporkus"
     "Hornfels" "Hoti" "Hsnanddsnhsn" "Hort" "Hotroderick" "Hotelmanager"
     "Howardstevens" "Howzit" "Huey" "Huffnpuff" "Huhwhat" "Hulu"
     "Iceclimbers" "Icy" "Iggyfilmcharacteriggy" "Iggykoopa" "Igor"
     "Iguanagon" "Ike" "Ikethesupermariobrossupershowike" "Ilpiantissimo"
     "Imanomario" "Imperialpoobah" "Indianajoe" "Inga" "Inkadinkadoo"
     "Inspectorgadget" "Inviso" "Ironsider" "Isaacnewton" "Isabelle"
     "Ishnail" "Isledelfinopolice" "Issh" "Jabble" "Jackcharacterjack"
     "Jagger"
     "Mushroommarauderandjakethecrusherfungusjakethecrusherfungus"
     "Jakethewatchman" "Jamano" "Jamesblond"
     "Jimmysfolksfamilymembersjamest" "Jimmysfolksfamilymembersjamiet"
     "Janbi" "Jarvis" "Jasonbateman" "Jasperoid" "Jeanclaudetruchet"
     "Jeffgriffeath" "Jellybobwariolandjellybob" "Jellyfishsisters"
     "Jerrypapermariothethousandyeardoorjerry"
     "Jerrymarioluigibowsersinsidestoryjerry" "Jessica" "Jet"
     "Jetsonicthehedgehogjetthehawk" "Jibberjaycharacterjibberjay"
     "Jigglypuff" "Boardssupermariogalaxyjillboardjillboard" "Jimlange"
     "Jimmyp" "Jimmyt" "Jimmysfolks" "Jinx" "Jodie" "Joanofarc" "Joe"
     "Joemariogolfseriesjoe" "Johanngutenberg" "Johnnydeepend"
     "Listofimpliedcharactersjohnsonairshipcrewmanjohnsonairshipcrewman"
     "Listofimpliedcharactersjohnsonxnautjohnsonxnaut"
     "Johnsonsuperpapermariojohnson" "Jojora" "Jojorasfriends" "Joker"
     "Jolene" "Joliet" "Romanosfatherandjolietsfatherjolietsfather"
     "Jonathanjones" "Josephhaydn" "Joy" "Jrklaptrap" "Jrtroopa"
     "Juansebastiandelcano" "Juliuscaesar" "Juneandward"
     "Donkeykongjrjuniorii" "Juniortheadventuresofsupermariobrosjunior"
     "Juniorsmomanddadjuniorsdad" "Juniorsmomanddadjuniorsmom"
     "Juniorshrooboid" "Junker" "Junklomp" "Juppi" "Justicetoad" "Klumsy"
     "Kaijumario" "Kaley" "Kalmar" "Kalypso" "Kamek" "Kamekkrew" "Kamella"
     "Kment" "Kammykoopa" "Kangaroo" "Kanya" "Kaos" "Kaptainskurvy"
     "Karatekong" "Karla" "Kass" "Katanakat" "Kate" "Katsini" "Kazooie"
     "Ken" "Kenmasters" "Kenthereporter" "Kenneth" "Kentckoopa" "Kerozene"
     "Kerrie" "Kersti" "Kevin" "Keyzer" "Kid" "Kidklown" "Kiddykong"
     "Killerkittyofthekaskervilles" "Kingbobomb" "Kingboo"
     "Kingboosupermariosunshinekingboo" "Kingcalamari" "Kingcroacusi"
     "Kingcroacusiii" "Kingcroacusiv" "Kingdedede" "Kingfret" "Kingjames"
     "Kingk" "Kingkrool"
     "Listofimpliedcharacterskingkoopasgreatgreatgrandkoopkingkoopasgreatgreatgrandkoop"
     "Kingkaliente" "Kingkutout" "Kingmacfrights" "Kingmackerel"
     "Kingneptune" "Kingnimbus" "Kingolly" "Kingsammer" "Kingtetris"
     "Kingtotomesu" "Kingvirus" "Kingwatinga" "Kingwindbag" "Kingzing"
     "Kings" "Kinokosennin" "Kinoppe" "Kip" "Kirby" "Kiryl" "Kitty" "Kkdu"
     "Klepto" "Klevar" "Klsn" "Klump" "Kleever" "Klubba" "Kludge"
     "Knifeguy" "Knowitalltoadpapermariocolorsplashknowitalltoad"
     "Knucklesknucklestheechidna" "Kolorado" "Koloradosfather"
     "Koloradoswife" "Kongfamily" "Kongfucharacterkongfu" "Koopa"
     "Koopageneral" "Koopakid" "Koopakoot" "Koopakrag" "Koopamaster"
     "Koopaparatroopatrio" "Koopashepherdess" "Koopatrol" "Koopathequick"
     "Koopalings" "Kooper" "Koopiekoo" "Thekoopinator" "Koopley" "Koopook"
     "Koops" "Koover" "Kopter" "Kpkoopas" "Kreepykrow" "Kritter" "Kroop"
     "Kroc" "Kroctopus" "Krow" "Kruller" "Krunch" "Krushacharacterkrusha"
     "Krushy" "Kublaikhan" "Kudgel" "Kungfukoopa" "Kuribo" "Kuroneko"
     "Kutlasscharacterkutlass" "Kuzzle" "Kyle" "Kyliekoopa"
     "Kyodaitogemetto" "Kyoko" "Kyon" "Ladybow" "Ladylima" "Lahla" "Laki"
     "Lakilester" "Lakilulu" "Lakithunder" "Lakitubros" "Lankykong"
     "Largefry" "Larrykoopa" "Larson" "Lavapiranha" "Ledger" "Lee"
     "Legendarycaptain" "Lemmykoopa" "Lena" "Leo" "Leonardodavinci"
     "Lightfish" "Lighthousekeeper" "Lilogre" "Lilmassif"
     "Lilypapermariolily" "Lilysuperpapermariolily" "Linda" "Link" "Lisa"
     "Littlemac" "Littlemousercharacterlittlemouser" "Littlet" "Liz"
     "Lizardon" "Llama" "Lordcrump" "Lordfredrik" "Loualbano"
     "Louispasteur" "Loyalpoplin" "Lubba" "Lucario" "Lucas" "Lucina"
     "Lucky" "Ludwigvanbeethoven" "Ludwigvonkoopa" "Luigeena" "Luigi"
     "Luigisgirlfriend" "Luigikongchnji" "Dinoriderslulu" "Lulu" "Lumalee"
     "Lumpy" "Luvbi" "Lydia" "Lylealzado" "Mamoleandpamole" "Machogrubba"
     "Mad" "Madadder" "Madbomber" "Madhatmki" "Madhatmkii" "Madhatmkiii"
     "Madjack" "Madpiano" "Madscienstein" "Madamagogo"
     "Madamebwahstrellacharactermadamebwahstrella" "Madameclairvoya"
     "Madzilla" "Madzillasmom" "Magikoopamasters" "Magnusvongrapple"
     "Magnusvongrapple" "Mahatmagandhi" "Mahgo" "Mailtoad"
     "Listofimpliedcharactersmaitredelishmaitredelish" "Majorburrows"
     "Mallow" "Mamafireplant" "Mamakurara" "Mamamario"
     "Jimmysfolksfamilymembersmamat" "Mamar" "Mametchi" "Manager"
     "Mangylox" "Manta" "Maple" "Marbald" "Marchingmilde" "Marcopolo"
     "Marianne" "Marilyn" "Marilynthesupermariobrossupershowmarilyn"
     "Mario" "Mariofilmcharactermario" "Mariojoeandluigibob"
     "Markmariotennisseriesmark" "Marknesopentournamentgolfmark" "Marth"
     "Maryo" "Marytoddlincoln" "Mason" "Mastercrash" "Masterduff"
     "Masterhand" "Masterlob" "Masterstinger" "Mastermantis" "Masternecky"
     "Masterneckysnr" "Masterpoet" "Masterpoplin" "Matchan"
     "Maudeandflomaude" "Maxmilliplatt" "Mayoracheever" "Mayorbernstein"
     "Mayorcellout" "Mayorchasen" "Mayorcook" "Mayordour"
     "Mayordovetegetter" "Mayorfettuccine" "Mayorfroobnitz"
     "Mayorgrenewetzki" "Mayorgriffeath" "Mayorimaworrywart" "Mayorlaabs"
     "Mayorlanslide" "Mayorlinguine" "Mayorlsismore" "Mayorkotzenberg"
     "Mayormccarthy" "Mayormcchan" "Mayormunchkins" "Mayorokleeder"
     "Mayorsidley" "Mayorsmallburg" "Mayorofnewyorkcity" "Mayorpenguin"
     "Mayorschmutznikov" "Mayorsidley" "Mayorsinger" "Mcballyhoo"
     "Mcgoomba" "Meanemcee" "Meg" "Megagoombabossmegagoomba" "Megakoopa"
     "Megaman" "Megasmilax" "Melcharactermel" "Melodypianissima"
     "Mekakuppa" "Mekakurib" "Merle" "Merlee"
     "Tribeofancientsmerlightmerlight" "Tribeofancientsmerlimbismerlimbis"
     "Merlon" "Tribeofancientsmerloomerloo" "Merlow" "Merlumina"
     "Merluvlee" "Mermaid" "Mervin" "Metaknight"
     "Metalmariosupersmashbrosmeleemetalluigi" "Metalmario" "Mettooyakata"
     "Mewtwo" "Michaelfaraday" "Michelangelobuonarroti" "Micki"
     "Microphone" "Midbus" "Midnite" "Mightyplumber" "Mii"
     "Mikhailsgorbachev" "Mike" "Tailsmilestailsprower" "Millenniumstar"
     "Millivanilli" "Mimi" "Minamotonoyoritomo" "Mindbogglers" "Minht"
     "Minibowser" "Minibowserjr" "Minididdykong" "Minirosalina" "Minispek"
     "Miniyoshi" "Minit" "Miniyoshi" "Toadministerminister"
     "Listofimpliedcharactersministercrepeministercrepe"
     "Ministerofmassage" "Minmei" "Minmin" "Minnie" "Minotaur" "Mips"
     "Misaki" "Missendless" "Misspetunia" "Misspersimmonohara" "Misstar"
     "Missy" "Mitsy" "Miyuki" "Mohog" "Moai"
     "Listofimpliedcharactersmoldymoldy" "Moleminermax"
     "Moltztheverygoonie" "Momma" "Mompiranha" "Mona"
     "Monaclubnintendomona" "Monaspetsmonasbear" "Monaspetsmonaselephant"
     "Monaspetsmonasmonkey" "Monaspetsmonaspig" "Monettes" "Monstar"
     "Monstercharactermonster" "Monsterflower" "Monstermama" "Montybros"
     "Monzo" "Moogle" "Mort" "Mortt" "Morty" "Mortonkoopajr" "Motherbrain"
     "Mountainsage" "Motherpenguin" "Mouser" "Mousersaurusrex"
     "Mousimilian" "Moustafa" "Mouthoftheriver" "Mremariopartyadvancemre"
     "Mrepapermariomre" "Mreraser" "Mrgamewatch" "Mrgibbel" "Mrhammer"
     "Mrhoggle" "Mrl" "Mrlevison" "Mrluggs" "Mrmayor" "Mrpresident"
     "Mrthwomp" "Mrx" "Mrsgammliss" "Mrsperiwinkle" "Mrspresident"
     "Mrsshroomlock" "Mrsthwomp" "Msmowz" "Mspacman" "Mssrboo"
     "Muddybuddy" "Muddee" "Muffyf" "Muffyf" "Mugga" "Mummipokey" "Murphy"
     "Mushbert" "Mushroomboy" "Mushroomgenie" "Mushroomjeanie"
     "Mushroomking"
     "Mushroommarauderandjakethecrusherfungusmushroommarauder"
     "Mushroomnanny" "Mushroomrebel" "Mushroomreferee" "Mushroomshopclerk"
     "Musicalnote" "Muskular" "Musst" "Mustardcafchef"
     "Mutantninjasentainokonokoman" "Mutekikyodaipakkun" "Mynx" "Mythra"
     "Nabbit" "Nanchandshi" "Nana" "Nankinkun" "Napple" "Nastasia"
     "Navalpiranha" "Neil" "Ness" "Netty" "Neville" "Nibbla"
     "Nicoleeggert" "Nikkilindseyginny" "Nifft"
     "Ninamariotennisseriesnina" "Ninasupermariomakernina"
     "Ninjacharacterninja" "Ninjakong" "Nob" "Nokielder" "Nokigrandson"
     "Nolrem" "Nora" "Noritake" "Norman" "Nomadimousecharacternomadimouse"
     "Notso" "Novbi" "Numchuckthemonkey" "Nutsoglobin" "Ochunks" "Oaklie"
     "Obiwantoadi" "Octo" "Octoblazooka" "Octopuscharacteroctopus"
     "Octopusboss" "Ojsanandobsan"
     "Listofimpliedcharactersoldmanskoooldmanskoo" "Oldmanwatchitt"
     "Oldredmug" "Olivia" "Om" "Omninom" "Onnanoko" "Oogtar" "Orbulon"
     "Orco" "Sama" "Otto" "Outbackmayor" "Oyazi" "Papatch" "Pacman"
     "Pakederm" "Pakkunmogura" "Palutena" "Pam" "Pammatteson" "Papamario"
     "Papaorb" "Jimmysfolkspapat" "Parakarry" "Parkdirector"
     "Parkstreetresidents" "Parrotcharacterparrot" "Parrotor"
     "Parrycharacterparry" "Partrick" "Patchcharacterpatch" "Patches"
     "Pattythesupermariobrossupershowpatty" "Pattysaturdaysupercadepatty"
     "Pattysmotherandfatherpattysfather"
     "Pattysmotherandfatherpattysmother" "Paula" "Pauline" "Peeka"
     "Peeweepiranha" "Penguinbosspenguin" "Penguinking" "Penguinpatrol"
     "Penguru" "Listofimpliedcharacterspengwenpengwen" "Pennington"
     "Penny" "Pentabros" "Perry" "Pesce" "Peteypiranha" "Petuni" "Petunia"
     "Pflower" "Phantamanta" "Phantombossphantom"
     "Boardssupermariogalaxyphilboardphilboard" "Piilloper" "Pianta"
     "Piantajudge" "Piantamayor" "Piantaprosecutor" "Piccolo" "Pichu"
     "Pierrepaulemileroux" "Pikachu" "Pikmin" "Pierre" "Pietro" "Pine"
     "Pinetjr" "Pinetsr" "Pinkgoldpeach" "Pipecreatures" "Pipeman" "Pipsy"
     "Piper" "Pirabbidplant" "Piranhabean" "Piranhasue" "Pitcharacterpit"
     "Pitta" "Plato" "Platypunk" "Plennt" "Plessie" "Plok" "Plum" "Podler"
     "Podley" "Pokerfaces" "Pokeytriplets" "Pola" "Polari" "Pollyroger"
     "Polterkitty" "Pompom" "Pompy" "Poobahthepharaoh" "Poochie" "Poochy"
     "Pook" "Pookie" "Poolopus"
     "Listofimpliedcharacterspoopalakoopapoopalakoopa" "Popdiva" "Popple"
     "Theporkloins" "Porcupufferbossporcupuffer" "Porter" "Portraitghost"
     "Posie" "Powert" "Postmaster" "Prtoad" "Princessa" "Princecroacus"
     "Princedreambert" "Princeflorian" "Princehugo" "Princemush"
     "Princemushroomkhamen" "Princepeasley" "Princepine" "Princepompadour"
     "Princesspapermariocolorsplashprincess"
     "Princesspapermariotheorigamikingprincess" "Princessdaisy"
     "Princessdaisyfilmcharacterprincessdaisy" "Princessdaisysfather"
     "Listofimpliedcharactersprincesseclairprincesseclair" "Princesslipid"
     "Princesspeach" "Princessshokora" "Princessshroob" "Princesszelda"
     "Priscillathepeckish" "Privategoomp" "Privatekoopa" "Profkinopio"
     "Professorchops" "Professorconnect" "Professorelvingadd"
     "Professorfrankly" "Professorfungi" "Pronto" "Prospector"
     "Psychokamek" "Puck" "Puff" "Puftoss"
     "Pukupukuwarioblastfeaturingbombermanpukupuku" "Punchinello"
     "Pungent" "Pungry" "Punielder" "Punio" "Puniper" "Punkrocks"
     "Putridpiranha" "Putts" "Pyoro" "Pyra" "Quawks" "Queenb" "Queenbean"
     "Queencroacusii" "Queenelizabethi" "Queenjaydes" "Queenmerelda"
     "Queenmushroomkhamen" "Queennimbus" "Queenrotunda" "Rabbidcranky"
     "Rabbidkong" "Rabbidluigi" "Rabbidmario" "Rabbidpeach"
     "Rabbidrosalina" "Rabbidyoshi" "Raini" "Ramensesii" "Rambi"
     "Raphaelsanzio" "Raphaeltheraven" "Raspberry" "Ratagator" "Rattly"
     "Ratso" "Rawkhawk" "Ray" "Raz" "Razor" "Reallygnawty" "Rebbi"
     "Redsuperpapermariored" "Redwariowareseriesred"
     "Redbluegoombabrosredgoomba" "Redbriefj"
     "Redbobombcharacterredbobomb" "Koopabrosredninjakoopa" "Rescuesquadv"
     "Residentdemon" "Richardburbage" "Richterbelmont" "Ridley" "Ringo"
     "Ripcheato" "Robstone" "Robin" "Robirdo" "Robomario" "Robokritter"
     "Robomouse" "Robotprincess" "Rob" "Rockpaperwizard"
     "Dinoridersrockman" "Rocko" "Rollanratl" "Romano"
     "Romanosfatherandjolietsfatherromanosfather" "Rookie"
     "Rogerthepottedghost" "Roguehog" "Rougerougethebat"
     "Rosetowninnkeeper" "Rosie" "Rosalina" "Rowfandrhuff"
     "Rowdyroddypiper" "Roxanne" "Royfireemblemroy"
     "Roymariotennispowertourroy" "Roykoopa" "Royalbusdriver" "Royalcow"
     "Royalparrot" "Royalsociety" "Rozary" "Rubberband" "Rudy" "Russt"
     "Ryu" "Sacre" "Sacredflamebeast" "Saffron" "Salout"
     "Salvadordrainotto" "Salvotheslime" "Sammi" "Samspook" "Sammyrai"
     "Samusaran" "Samshalam" "Sandbird" "Sandworm" "Santaclaus"
     "Sarahbarnard" "Sarissa" "Sasha"
     "Listofimpliedcharacterssashimiesashimie" "Sass" "Sassysquatch"
     "Scarlette" "Scissorsbossscissors" "Scoff" "Scooter"
     "Scratchythefrobug" "Screamy"
     "Screechdonkeykongcountrydiddyskongquestscreech"
     "Screechmariorabbidssparksofhopescreech" "Scruffroc" "Seadevil"
     "Sean" "Secretagentn" "Seizer" "Sensei" "Seormayor" "Sephiroth"
     "Sergeantflutter" "Sergeantguy" "Sergeantkooperman" "Serpci"
     "Servant" "Sewerguru" "Sewerrat" "Sgtslaughter" "Shadoo"
     "Shadowmario" "Shadowqueen" "Shadowsirens" "Shadowthedog"
     "Shadowcharactershadowthehedgehog" "Shakeking" "Shawn" "Sheik"
     "Shellshockers" "Sheri" "Sherry" "Shisai" "Shivers" "Shoot"
     "Shopowner" "Shopkeeperpolario" "Shchnogerman"
     "Satoruiwatashopmanageriwata" "Shabbadoo" "Shroob" "Shrooboidbrat"
     "Shroomlock" "Shulk" "Shurikenthefalcon" "Shybandit"
     "Shyguymariopartyshyguy" "Shyguywell" "Shysquad" "Sickobratz" "Silky"
     "Silversilverthehedgehog" "Sipsi" "Sirgrodus" "Sirswoop" "Sirweston"
     "Skeetcharacterskeet" "Skeletonkey" "Skipper" "Skolar" "Skowl"
     "Slammercharacterslammer" "Slimpixlslim" "Slimflopsideslim"
     "Slimbankshot" "Slimedragonquestslime" "Sluggytheunshaven" "Smelter"
     "Smilax" "Smithy" "Smokeythedragon" "Smookers" "Smorg" "Snide"
     "Snifitpatrol" "Snorkelsnake" "Snowking" "Snowspirits" "Solidsnake"
     "Sonicsonicthehedgehog" "Sonnysaturdaysupercadesonny"
     "Sonnymariogolfsonny" "Sophia" "Sora" "Soundfrog" "Spangle"
     "Sparkycharactersparky" "Spearmask" "Speardovich"
     "Sphinxcharactersphinx" "Sphinxz" "Spideraticus"
     "Spikemariotennisspike" "Spikefilmcharacterspike" "Spikestorm"
     "Spikyjoe" "Spikyjohn" "Spikytom" "Spindel" "Spiritofcuteness"
     "Spiritoffright" "Spiritofgreed" "Spiritofkindness" "Spiritofpower"
     "Spiritofspeed" "Spiritwholovessurprises" "Dribblespitzspitz"
     "Spoiledrotten" "Spookycharacterspooky" "Spookyspeedster"
     "Listofimpliedcharacterssporekingsporeking" "Sprixieprincesses"
     "Squiddicus" "Squawks" "Squitter" "Squirtbosssquirt" "Stanley"
     "Stanleypapermariostanley" "Stanleythetalkingfish"
     "Staplerbossstapler" "Starchildren" "Starspirits" "Startemplegate"
     "Starworldleader" "Starfy" "Starfish" "Starlow" "Starshadebros"
     "Steamer" "Stevenesopentournamentgolfsteve" "Steveminecraftsteve"
     "Stewardluigismansionsteward" "Stewardpapermariostickerstarsteward"
     "Stewart" "Stoolpigeon" "Stock" "Stork" "Stuffwell" "Stuffytheth"
     "Submarinecaptain" "Suepea" "Suikahime" "Sullivan" "Sultan"
     "Sultanpasbah" "Sumbi" "Sumokong" "Sun" "Sundreamstone"
     "Sunglassesvendor" "Sunnycide" "Sunsetexpressconductor"
     "Superblooperbosssuperblooper" "Supercooljake" "Superkong"
     "Superplantcharactersuperplant" "Superteam" "Surfingkinopio"
     "Susannaross" "Sushie" "Sutakichi" "Suuchan" "Sven" "Swankykong"
     "Sweetlopek" "Swiggler" "Swindell" "Swob"
     "Sylviapapermariothethousandyeardoorsylvia"
     "Sylviamariotennispowertoursylvia" "Tt" "Tabuu" "Tadrock" "Taj"
     "Takaaki" "Takeshi" "Talkingparrot" "Tamagodon" "Tamao"
     "Tammytreehugger" "Tangerinogrillchef" "Taptapthegolden"
     "Taptaptherednose" "Tapebosstape" "Tatanga" "Tashrooba" "Tawks"
     "Tawnytyler" "Taycet" "Tbear" "Teapartytoads" "Teambabyyoshi" "Tecxx"
     "Tedbull" "Terrormisu" "Terrybogard" "Tetristribe" "Tfvfanclub"
     "Thak" "Thechimp" "Thecreepysteepleboo" "Thefloatingwhirlindas"
     "Thefork" "Theinterchet" "Theinterned" "Themaster"
     "Theoldpsychicladytheoldpsychicladywiththeevileyewhoreadsfortunesandknowseverythingbeforeithappens"
     "Thermidor" "Thomasedison" "Thomasjefferson" "Thoreau" "Thread"
     "Threehags" "Threelittlepigheads" "Thrifft" "Thudley" "Thugly"
     "Thunderbirdo" "Thundercloudwarioblastfeaturingbombermanthundercloud"
     "Thunderroc" "Firebrandandthunderhandthunderhand" "Thwompbros"
     "Tiara" "Tikitong" "Timber" "Timbersparents" "Tinga"
     "Tinymariogolfseriestiny" "Tinykong" "Tinyspinies" "Tippi" "Tiptron"
     "Listofimpliedcharacterstiptronmkiitiptronmkii" "Tiptup" "Toad"
     "Toadinthedesert" "Toadscousin" "Toadbert" "Toadette" "Toadia"
     "Toadiko" "Toadman" "Toadmastergeneral" "Toadofsky" "Toadster"
     "Toadsworth" "Toadsworththeyounger" "Toadgeneral" "Toadvillager"
     "Tocet" "Todojewski" "Tolielip" "Tolstar" "Tommylasagna"
     "Tommytreehugger" "Tonypapermariothethousandyeardoortony"
     "Tonynesopentournamentgolftony" "Toodles" "Toonlink" "Topman"
     "Topmaniac" "Torchtusk" "Tori" "Torquecharactertorque"
     "Listofimpliedcharacterstoxictoadztoxictoadz" "Toymonster"
     "Tradingeventtoad" "Travelingsisters" "Treasurehuntingtoad"
     "Tribeofancients" "Trickythetriceratops" "Triplets" "Troff"
     "Tryclyde" "Tsailun" "Tubbablubba" "Tubbasheart" "Tuki" "Tumble"
     "Turrettusk" "Tutankoopa" "Tuxie" "Twila" "Twink"
     "Tyrannosaurustwins" "Ug" "Ultrabarreldk" "Ultrapukupuku"
     "Uncleamiibo" "Unclearthur" "Unclegrimmly" "Unclekong" "Uncletony"
     "Underchomp" "Undergruntgunner" "Undodog" "Unnamedworldsachuman"
     "Urayoshi" "Valentina" "Vampawhite" "Vanessa" "Vannat" "Vaultguard"
     "Vectorvectorthecrocodile" "Verygnawty" "Villageleader" "Villager"
     "Vincentvangore" "Vinny" "Violetpassagecaptain" "Vivian" "Vizorman"
     "Waluigi" "Wanda" "Waldothewizard" "Walter" "Wario" "Wariosfather"
     "Wariosmother" "Wariobug" "Warioman" "Wariomensakana" "Wart" "Watt"
     "Webber" "Welderberg" "Wendyokoopa" "Whacka" "Whalecharacterwhale"
     "Whibbi" "Whittle" "Whisker" "Whispywoods" "Whitemage" "Whiteshyguy"
     "Whompking" "Wigglersupermariosunshinewiggler" "Wigglerfamily"
     "Wildsting" "Wiifittrainer" "Williamshakespeare" "Willy" "Wingo"
     "Wingsofnight" "Winkle" "Winky" "Winnieandsummer" "Winnie"
     "Winterwindster" "Wisdurm" "Wisewisterwood" "Witchbosswitch"
     "Wizenheimer" "Wizakoopa" "Wizardkingofthewest" "Wizpig"
     "Wolfodonnell" "Wolfenboss" "Wolfgangamadeusmozart" "Wonky" "Woodrow"
     "Woody" "Woodswatchers" "Wooster" "Worm" "Wormwould"
     "Wrestlinggorilla" "Wringer" "Wrinklykong" "Xananab" "Yakkey"
     "Yamamura" "Yangus" "Yebbi" "Koopabrosyellowninjakoopa"
     "Yellowtoadandbluetoadyellowtoad" "Yellowtoadtoadbrigadeyellowtoad"
     "Yikk" "Yokk" "Yoob" "Yoshi" "Yoshiislandspirits" "Youngcricket"
     "Younglink" "Youngmcdonald" "Yukiosawada" "Zangief" "Zeekeeper"
     "Zesst" "Zero" "Ziptoad" "Zombone")
    (steampunk
     "Geargene" "Phineascog" "Brassley" "Cogswell" "Cogsworth" "Cogsworth"
     "Cogroy" "Cogson" "Vyncog" "Gearrandy" "Gearwayne" "Gearijah"
     "Gearwill" "Gearbert" "Coggan" "Coglan" "Cogsworth"
     "Gearbriel" "Brassley" "Cogsby" "Brycegear" "Gearhart" "Jordgear"
     "Lorentius" "Artifex" "Cogglyn" "Gearold" "Cogarl" "Gearald"
     "Gearshan" "Austonius" "Terrarius" "Cogger" "Coggith" "Christogear"
     "Waltair" "Gearmiah" "Etheron" "Cogsworth" "Kyleridge" "Pierton"
     "Coglass" "Zacharion" "Gearhenry" "Coggathan" "Gearadam" "Cogseph"
     "Aethergear" "Cogler" "Gearry" "Dennius" "Cogsworth" "Raymgear"
     "Gearhart" "Gearick" "Cogsander" "Geargory" "Samuetron" "Cogsmin"
     "Brassdon" "Scottius" "Jettin" "Larrovius" "Gearphen" "Gearthan"
     "Gearic" "Nickelius" "Gearius" "Cogjac" "Cogryan" "Gearfrey"
     "Gearward" "Gearson" "Cogwald" "Cogsworth" "Geargeorge" "Briancog"
     "Coggvin" "Kenngear" "Gearshua" "Copperpaul" "Cogdrew" "Gearvin"
     "Donaric" "Coggmark" "Gearthonius" "Gearthew" "Geariel" "Cogsworth"
     "Cogstopher" "Thomgear" "Cogsworth" "Gearhart" "Willgear" "Gearvid"
     "Cogwell" "Gearjohn" "Cogbert" "Gearmes")
    (modern
     "James" "Robert" "John" "Michael" "David" "William" "Richard"
     "Joseph" "Thomas" "Christopher" "Charles" "Daniel" "Matthew"
     "Anthony" "Mark" "Donald" "Steven" "Andrew" "Paul" "Joshua" "Kenneth"
     "Kevin" "Brian" "George" "Timothy" "Ronald" "Jason" "Edward"
     "Jeffrey" "Ryan" "Jacob" "Gary" "Nicholas" "Eric" "Jonathan"
     "Stephen" "Larry" "Justin" "Scott" "Brandon" "Benjamin" "Samuel"
     "Gregory" "Alexander" "Patrick" "Frank" "Raymond" "Jack" "Dennis"
     "Jerry" "Tyler" "Aaron" "Jose" "Adam" "Nathan" "Henry" "Zachary"
     "Douglas" "Peter" "Kyle" "Noah" "Ethan" "Jeremy" "Walter" "Christian"
     "Keith" "Roger" "Terry" "Austin" "Sean" "Gerald" "Carl" "Harold"
     "Dylan" "Arthur" "Lawrence" "Jordan" "Jesse" "Bryan" "Billy" "Bruce"
     "Gabriel" "Joe" "Logan" "Alan" "Juan" "Albert" "Willie" "Elijah"
     "Wayne" "Randy" "Vincent" "Mason" "Roy" "Ralph" "Bobby" "Russell"
     "Bradley" "Philip" "Eugene"
     )
    ))

(defconst fig//medieval-titles
  '(("knight" . "Sir")
    ("king" . "King")
    ("queen" . "Queen")
    ("duke" . "Duke")
    ("duchess" . "Duchess")
    ("count" . "Count")
    ("earl" . "Earl")
    ("countess" . "Countess")
    ("viscount" . "Viscount")
    ("viscountess" . "Viscountess")
    ("baron" . "Baron")
    ("baroness" . "Baroness")
    ("marquis" . "Marquis")
    ("marquess" . "Marquess")))

(defconst fig//era-jobs
  `((medievaltimes
     "peasant" "blacksmith" "fletcher" "jester" "squire" "knight" "king" "queen" "duke" "duchess" "count" "earl" "countess" "viscount" "viscountess" "baron" "baroness" "marquis" "marquess")
    (ageofsail
     "pirate" "buccaneer" "privateer" "freebooter" "corsair" "plunderer" "swashbuckler" "captain"
     "smuggler" "stowaway" "Thief, Ocean" "conquistador" "first mate" "quartermaster" "plank walker"
     "parrot" "scullery worker" "galley cook" "cabin boy" "sharp watch" "poop-deck swabber" "navigator"
     "cartographer" "helmsman" "peg leg warmer" "gunner" "shipwright" "admiral" "hook sharpener"
     "grog somellier" "sail dewrinkler" "cannon lubricator")
    (renaissance
     "painter" "sculptor" "playwright" "patron" "ninja" "plumber"
     "statue polisher" "paint thinner" "sculpture model" "statue"
     "plague carrier" "bishop" "baker" "fencer" "fence" "thief"
     "Italian" "guy who paints himself silver and wears a tophat"
     "actor" "silk trader" "Rhonaldinho" "the first ever atheist"
     "poet" "painting hanger" "composer" "illuminati cofounder and product mommy"
     "wimbeldon tournamentor" "tailor" "co-conspirator" "art contemplator"
     "fake wizard" "pope" "socialite" "executioner" "alchemist" "scientist (galvanic energy)"
     "electric fish tickler" "artificer"
     )
    (steampunk
     "gearmaker" "boilermaker" "pipemaker" "airship pilot" "engineer" "train engineer" "slap bassist"
     "dashing rogue" "idle gentleman" "good sir" "highwayman" "big daddy"
     "Federal government contractor with steampunk.com" "gear polisher" "witch hunter"
     "derigible inflator" "twitching steamer" "tin snip" "bellows enjoyer" "Valve employee"
     "chimney sweep" "poor starving orphan child" "bearing bearer" "tophat designer" "dossier griefer"
     "joint joiner"
     )
    (modern
     "Clonkhead and Clonk Head"
     "Free Software Advocate, Unpaid"
     "Livestreamer (VTuber)"
     "VTweeter"
     "Livestreamer (Flesh)"
     "Forex Trader and Crypto Trader"
     "Prompt Engineer and AI Artist"
     "Spellcrafter, Enchanter, Wizard Or Other Majekkal Practitioner"
     "Leetcode Grinder"
     "Rickshaw Coolie"
     "TikToker and Tick Toker"
     "Collector Of Sentimental Artifacts Except Collectors of Valuable Artifacts"
     "Collector Of Valuable Artifacts"
     "Minecraft YouTube Twitter Poster"
     "First-Line Supervisor of Construction Trades and Extraction Worker"
     "Automotive Service Technicians and Mechanic"
     "Computer User Support Specialist"
     "Industrial Truck and Tractor Operator"
     "Human Resources Specialist"
     "Financial Manager"
     "Police and Sheriff's Patrol Officer"
     "Electrician"
     "Lawyer"
     "Licensed Practical and Licensed Vocational Nurse"
     "Market Research Analysts and Marketing Specialist"
     "Carpenter"
     "Medical Assistant"
     "Shipping, Receiving, and Inventory Clerk"
     "Management Analyst"
     "Food Preparation Worker"
     "Maids and Housekeeping Cleaner"
     "Landscaping and Groundskeeping Worker"
     "First-Line Supervisors of Food Preparation and Serving Worker"
     "Light Truck Driver"
     "Receptionists and Information Clerk"
     "Construction Laborer"
     "Sales Representative of Services, Except Advertising, Insurance, Financial Services, and Travel"
     "Secondary School Teacher, Except Special and Career/Technical Education"
     "Security Guard"
     "First-Line Supervisor of Retail Sales Worker"
     "Cooks, Restaurant"
     "Teaching Assistant, Except Postsecondary"
     "Accountant and Auditor"
     "Sales Representative, Wholesale and Manufacturing, Except Technical and Scientific Product"
     "Maintenance and Repair Worker, General"
     "Elementary School Teacher, Except Special Education"
     "Nursing Assistant"
     "First-Line Supervisor of Office and Administrative Support Worker"
     "Bookkeeping, Accounting, and Auditing Clerk"
     "Project Management Specialists and Business Operations Specialist, All Other"
     "Software Developer and Software Quality Assurance Analyst and Tester"
     "Heavy and Tractor-Trailer Truck Driver"
     "Secretaries and Administrative Assistant, Except Legal, Medical, and Executive"
     "Waiter and Waitress"
     "Janitor and Cleaner, Except Maids and Housekeeping Cleaners"
     "Stocker and Order Filler"
     "General and Operations Manager"
     "Office Clerk, General"
     "Laborer and Freight, Stock, and Material Mover, Hand"
     "Customer Service Representative"
     "Registered Nurse"
     "Cashier"
     "Fast Food and Counter Worker"
     "Retail Salespersons"
     )))

(defconst fig//era-nicknames
  '((medievaltimes
     "The Cruel" "The Impaler" "The Implyer" "The Hand" "The Dread" "The Vicious" "The Bad"
     "The Mean" "The Menace" "The Menacing" "The Violent" "The Loathsome" "The Fiend" "The Worm"
     "The Gambler" "The Drunk" "The Dragon" "The Tyrant" "The Despot" "The Dealer" "The Throngler"
     "The Unrepentant" "The Malodorous" "The Ugly" "The Glutton" "The Strangler" "The Brute"
     "The Wench" "The Monstrous"
     )
    (ageofsail
     "Depp" "The Cruel" "Sparrow" "Deep" "Stumpy" "Hook" "Cap's Favorite" "The Sober" "The Snitch"
     "Salty" "Saltine" "Bathtub" "Twinkle Toes" "Fishy" "Fish Guam"
     "No-Eye" "One-Eye" "Two-Eye" "Three-Eye"
     "No-Hands" "One-Hands" "Two-Hands" "Three-Hands"
     )
    (renaissance
     "Asagioli" "Bombieri" "Cagliostro" "Divini" "Eustachi" "Fracastoro" "Grimaldi"
     "The Big Cheese" "Aioli" "Etzio"
     )
    (steampunk
     "Indubitable" "Staunch" "The" "Von" "Van" "Uncanny"
     )
    (modern
     "Fishy" "Bloval" "Etchy" "Shringhi" "Neuland" "The Clam" "Joel" "Dew" "Chip" "Boofa" "Pookie"
     "Oomfie"
     )))
