(add-to-list 'load-path (f-canonical "./"))
(require 'fig-database)
(require 'fig-model)
(require 'fig-breed)
(require 'fig)
(require 'fig-rpg)
(require 'fig-semi)
(require 'fig-voice)
(require 'fig-emotes)
(require 'fig-bible)
(require 'fig-fakechat)
(require 'fig-obs)
(add-to-list 'load-path (f-canonical "./contrib/"))
(require 'bezelea-muzak)
(fig/connect)
