(add-to-list 'load-path (f-canonical "./"))
(require 'fig-sensitive)
(require 'fig-database)
(require 'fig-model)
(require 'fig-breed)
(require 'fig-hexamedia)
(require 'fig-gcp)
(require 'fig)
(require 'fig-geiser)
(require 'fig-rpg)
(require 'fig-semi)
(require 'fig-voice)
(require 'fig-emotes)
(require 'fig-bible)
(require 'fig-fakechat)
(require 'fig-twitch)
(require 'fig-bullfrog)
(require 'fig-obs)
(require 'fig-friend)
(require 'fig-curse)
(require 'fig-gdq)
(require 'fig-gl)
(require 'fig-bless)
(add-to-list 'load-path (f-canonical "./contrib/"))
(require 'bezelea-muzak)
(fig/connect)
